const PDFDocument = require('pdfkit-table');

/**
 * Generate Attendance Report PDF
 * @param {Object} res - Express response object
 * @param {Array} records - Attendance records
 * @param {Object} metadata - Metadata ({ title, subtitle, facultyName, date })
 */
const generateAttendancePDF = async (res, records, metadata = {}) => {
    const doc = new PDFDocument({ margin: 30, size: 'A4' });

    // Set headers
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=attendance_report_${Date.now()}.pdf`);

    doc.pipe(res);

    // Branding
    doc.rect(0, 0, doc.page.width, 50).fill('#4F46E5'); // Indigo header
    doc.fillColor('white').fontSize(20).text('GeoQR Attendance System', 30, 15);

    // Title & Metadata
    doc.moveDown(2);
    doc.fillColor('black').fontSize(16).text(metadata.title || 'Attendance Report', { align: 'center' });

    if (metadata.subtitle) {
        doc.moveDown(0.2);
        doc.fontSize(10).fillColor('#444').text(metadata.subtitle, { align: 'center' });
    }

    doc.moveDown(0.5);
    doc.fontSize(10).fillColor('gray');
    if (metadata.facultyName) doc.text(`Faculty: ${metadata.facultyName}`, { align: 'center' });
    if (metadata.date) doc.text(`Date: ${metadata.date}`, { align: 'center' });
    doc.text(`Generated on: ${new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })}`, { align: 'center' });
    doc.moveDown(2);

    // Summary
    const total = records.length;
    const present = records.filter(r => (r.status || '').toLowerCase() === 'present').length;
    const late = records.filter(r => (r.status || '').toLowerCase() === 'late').length;
    const absent = records.filter(r => (r.status || '').toLowerCase() === 'absent').length;

    doc.fontSize(12).fillColor('black').text('Summary:', 30);
    doc.fontSize(10).text(`Total Records: ${total} | Present: ${present} | Late: ${late} | Absent: ${absent}`, 30);
    doc.moveDown(1);

    if (records.length === 0) {
        doc.moveDown(2);
        doc.fontSize(14).fillColor('gray').text('No attendance records found for the selected filters.', { align: 'center' });
        doc.end();
        return;
    }

    // Table
    const table = {
        title: "Attendance Records",
        headers: ["Time", "Student Name", "Roll No", "Status", "Subject", "Location"],
        rows: records.map(r => [
            r.timestamp ? new Date(r.timestamp).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' }) : '--',
            r.student_name || 'Unknown',
            r.student_code || '--',
            (r.status || 'N/A').toUpperCase(),
            r.subject || '-',
            r.location_name || '--'
        ])
    };

    await doc.table(table, {
        prepareHeader: () => doc.font('Helvetica-Bold').fontSize(9),
        prepareRow: (row, indexColumn, indexRow, rectRow, rectCell) => doc.font('Helvetica').fontSize(9)
    });

    // Footer
    doc.fontSize(8).fillColor('#aaa').text('Generated by GeoQR System', 30, doc.page.height - 40, { align: 'center' });

    doc.end();
};

module.exports = { generateAttendancePDF };
